### ISSUE TITLE
cycles test 1

### ISSUE THREAD

**Issue by zy1o** [zy1o/testspace.getting-started#5]
Focus on a new Feature `ZYTO DEBIL`
```
testspace:
  branch: "zyto-kopyto"
  specs:
    - path: "hello.md"
    - path: "another_test.md"
    - path: "debil.md"
    ignore:
       - "syntax.examples.md"
       - "syntax.other_examples.md"
```
