### ISSUE TITLE
Release 2.3.4.5

### ISSUE THREAD

**Issue by zy1o** [zy1o/testspace.getting-started#8]
```
testspace:
  branch: "zyto-kopyto"
  specs:
    - path: "hello.md"
    - path: "another_test.md"
    ignore:
       - "syntax.examples.md"
```
